{
    "type": "bundle",
    "id": "bundle--360e289a-5a14-4643-9c2b-d09a53cc6b43",
    "objects": [
        {
            "type": "vulnerability",
            "spec_version": "2.1",
            "id": "vulnerability--efa3be7e-3c9a-46f4-a855-aedfd26d6574",
            "created_by_ref": "identity--8ce3f695-d5a4-4dc8-9e93-a65af453a31a",
            "created": "2025-03-19T00:39:28.644396Z",
            "modified": "2025-03-19T00:39:28.644396Z",
            "name": "CVE-2024-23943",
            "description": "An unauthenticated remote attacker can gain access to the cloud API due to a lack of authentication for a critical function in the affected devices. Availability is not affected.",
            "external_references": [
                {
                    "source_name": "cve",
                    "external_id": "CVE-2024-23943"
                }
            ]
        }
    ]
}