{
    "type": "bundle",
    "id": "bundle--03c1bf46-18b6-4d42-9fc0-5810e2f993bd",
    "objects": [
        {
            "type": "vulnerability",
            "spec_version": "2.1",
            "id": "vulnerability--c1dc1ab6-3f98-4442-bb56-ddc581775491",
            "created_by_ref": "identity--8ce3f695-d5a4-4dc8-9e93-a65af453a31a",
            "created": "2025-04-15T00:41:41.103868Z",
            "modified": "2025-04-15T00:41:41.103868Z",
            "name": "CVE-2025-32914",
            "description": "A flaw was found in libsoup, where the soup_multipart_new_from_message() function is vulnerable to an out-of-bounds read. This flaw allows a malicious HTTP client to induce the libsoup server to read out of bounds.",
            "external_references": [
                {
                    "source_name": "cve",
                    "external_id": "CVE-2025-32914"
                }
            ]
        }
    ]
}