{
    "type": "bundle",
    "id": "bundle--3a988ee3-bbb6-4369-9d94-174f96ed3a6c",
    "objects": [
        {
            "type": "vulnerability",
            "spec_version": "2.1",
            "id": "vulnerability--0a96027b-ba2a-4ef7-9576-69a32c9e0572",
            "created_by_ref": "identity--8ce3f695-d5a4-4dc8-9e93-a65af453a31a",
            "created": "2025-03-11T00:38:56.010725Z",
            "modified": "2025-03-11T00:38:56.010725Z",
            "name": "CVE-2025-1497",
            "description": "A vulnerability, that could result in Remote Code Execution (RCE), has been found in PlotAI. Lack of validation of LLM-generated output allows attacker to execute arbitrary Python code.\nVendor commented out vulnerable line, further usage of the software requires uncommenting it and thus accepting the risk. The vendor does not plan to release a patch to fix this vulnerability.",
            "external_references": [
                {
                    "source_name": "cve",
                    "external_id": "CVE-2025-1497"
                }
            ]
        }
    ]
}