{
    "type": "bundle",
    "id": "bundle--12f0f985-60ec-459e-bf0f-25b7cd6b50ca",
    "objects": [
        {
            "type": "vulnerability",
            "spec_version": "2.1",
            "id": "vulnerability--e5e8322a-93e1-429e-9009-3b1f6a986bc7",
            "created_by_ref": "identity--8ce3f695-d5a4-4dc8-9e93-a65af453a31a",
            "created": "2025-04-09T00:40:29.423003Z",
            "modified": "2025-04-09T00:40:29.423003Z",
            "name": "CVE-2025-32414",
            "description": "In libxml2 before 2.13.8 and 2.14.x before 2.14.2, out-of-bounds memory access can occur in the Python API (Python bindings) because of an incorrect return value. This occurs in xmlPythonFileRead and xmlPythonFileReadRaw because of a difference between bytes and characters.",
            "external_references": [
                {
                    "source_name": "cve",
                    "external_id": "CVE-2025-32414"
                }
            ]
        }
    ]
}