{
    "type": "bundle",
    "id": "bundle--18ae20dd-8521-4d2f-b7b4-501fd57c2e74",
    "objects": [
        {
            "type": "vulnerability",
            "spec_version": "2.1",
            "id": "vulnerability--67daaaea-6450-492e-8576-0b5a7c09872a",
            "created_by_ref": "identity--8ce3f695-d5a4-4dc8-9e93-a65af453a31a",
            "created": "2025-03-27T00:39:33.893131Z",
            "modified": "2025-03-27T00:39:33.893131Z",
            "name": "CVE-2025-31160",
            "description": "atop through 2.11.0 allows local users to cause a denial of service (e.g., assertion failure and application exit) or possibly have unspecified other impact by running certain types of unprivileged processes while a different user runs atop.",
            "external_references": [
                {
                    "source_name": "cve",
                    "external_id": "CVE-2025-31160"
                }
            ]
        }
    ]
}