{
    "type": "bundle",
    "id": "bundle--ed19e1db-101f-40d3-aa5c-48ff790147b7",
    "objects": [
        {
            "type": "vulnerability",
            "spec_version": "2.1",
            "id": "vulnerability--36c7de42-11dd-4876-9842-b5416b67128b",
            "created_by_ref": "identity--8ce3f695-d5a4-4dc8-9e93-a65af453a31a",
            "created": "2025-04-03T00:39:50.45187Z",
            "modified": "2025-04-03T00:39:50.45187Z",
            "name": "CVE-2025-21934",
            "description": "In the Linux kernel, the following vulnerability has been resolved:\n\nrapidio: fix an API misues when rio_add_net() fails\n\nrio_add_net() calls device_register() and fails when device_register()\nfails.  Thus, put_device() should be used rather than kfree().  Add\n\"mport->net = NULL;\" to avoid a use after free issue.",
            "external_references": [
                {
                    "source_name": "cve",
                    "external_id": "CVE-2025-21934"
                }
            ]
        }
    ]
}