{
    "type": "bundle",
    "id": "bundle--cbb122a5-28fc-488a-b625-3d6732d7ee07",
    "objects": [
        {
            "type": "vulnerability",
            "spec_version": "2.1",
            "id": "vulnerability--1cfa0d57-a42b-48c7-8962-18fac05567a3",
            "created_by_ref": "identity--8ce3f695-d5a4-4dc8-9e93-a65af453a31a",
            "created": "2025-05-30T00:42:51.494102Z",
            "modified": "2025-05-30T00:42:51.494102Z",
            "name": "CVE-2025-37995",
            "description": "In the Linux kernel, the following vulnerability has been resolved:\n\nmodule: ensure that kobject_put() is safe for module type kobjects\n\nIn 'lookup_or_create_module_kobject()', an internal kobject is created\nusing 'module_ktype'. So call to 'kobject_put()' on error handling\npath causes an attempt to use an uninitialized completion pointer in\n'module_kobject_release()'. In this scenario, we just want to release\nkobject without an extra synchronization required for a regular module\nunloading process, so adding an extra check whether 'complete()' is\nactually required makes 'kobject_put()' safe.",
            "external_references": [
                {
                    "source_name": "cve",
                    "external_id": "CVE-2025-37995"
                }
            ]
        }
    ]
}